version: '3'
services:
  # nginx-app:
  #   image: nginx
  # node:
  #   build:
  #     dockerfile: ./docker/node.dockerfile
  #     context: .
  #   image: node
  #   container_name: node_docker
  #   ports:
  #     - 3000:3000
  #   #     networks:
  #   #         - development-network
  #   volumes:
  #     - .:/home/node/app

  #   depends_on:
  #     - mysql

  mysql:
    image: mysql
    container_name: mysql_docker
    # networks:
    #   - development-network
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

# networks:
#   development-network:
#     driver: bridge

# volumes:
#   mysql_data:
#     driver: local
